easy_admin:
    entities:
      Category:
        class: App\Entity\Category
        list:
                fields: ['id', 'title', 'description', 'posts']
        
      User:
        class: App\Entity\User
        list:
          fields: ['id', 'username', 'email', 'roles', 'posts']
        
      Post:
        class: App\Entity\Post
        list:
          fields: ['id', 'title', 'category', 'user.username', 'createdAt', 'reports']

      Report:
        class: App\Entity\Report
        list:
          fields: ['id', 'post', 'user', 'content']

#    design:
#      assets:
#        css: 
#          - '/css/bootstrap.min.css'
#          - '/css/style.css'
