easy_admin:
    entities:
      Category:
        class: App\Entity\Category
        list:
                fields: ['id', 'title', 'description', 'posts']
        
      User:
        class: App\Entity\User
        list:
          fields: ['id', 'username', 'email', 'roles', 'posts']
        form:
          fields:
            - {property: 'username' }
            - {property: 'email' }
            - {property: 'roles' }
      Post:
        class: App\Entity\Post
        list:
          fields: ['id', 'title', 'category', 'user.username', 'createdAt', 'post_report']

    design:
      assets:
        css: 
          - '/public/css/bootstrap.min.css'
          - '/public/css/style.css'
