easy_admin:
    entities:
      Signalement:
        class: App\Entity\Report
        list:
          fields: ['id', 'post', 'user', 'content']

      Catégorie:
        class: App\Entity\Category
        list:
                fields: ['id', 'title', 'description', 'posts']
        
      Utilisateur:
        class: App\Entity\User
        list:
          fields: ['id', 'username', 'email', 'roles', 'posts']
        
      Publication:
        class: App\Entity\Post
        list:
          fields: ['id', 'title', 'category', 'user.username', 'createdAt', 'reports']

      Réponses:
        class: App\Entity\Comment
        list:
          fields: ['id', 'post', 'author', 'createdAt']

      

      

#    design:
#      assets:
#        css: 
#          - '/css/bootstrap.min.css'
#          - '/css/style.css'
